ancestor: null
releases:
  1.0.0:
    changes:
      bugfixes:
      - linting and formatting for CI
      minor_changes:
      - Add cli_parse module and plugins (https://github.com/ansible-collections/ansible.utils/pull/28)
      - Added fact_diff plugin and sub plugin
      - Added validate module/lookup/filter/test plugin to validate data based on
        given criteria
    fragments:
    - 23 linting and formatting.yaml
    - 28_cli_parse_plugins_add.yaml
    - 29-add_docs_for_Cli_parse.yaml
    - add_fact_diff.yaml
    - docs_copyedit.yaml
    - validate.yaml
    modules:
    - description: Parse cli output or text using a variety of parsers
      name: cli_parse
      namespace: ''
    - description: Find the difference between currently set facts
      name: fact_diff
      namespace: ''
    - description: Update currently set facts
      name: update_fact
      namespace: ''
    - description: Validate data with provided criteria
      name: validate
      namespace: ''
    plugins:
      lookup:
      - description: Retrieve the value in a variable using a path
        name: get_path
        namespace: null
      - description: Find the indices of items in a list matching some criteria
        name: index_of
        namespace: null
      - description: Flatten a complex object into a dictionary of paths and values
        name: to_paths
        namespace: null
      - description: Validate data with provided criteria
        name: validate
        namespace: null
    release_date: '2020-12-08'
  1.0.1:
    changes:
      minor_changes:
      - Move CHANGELOG.rst file under changelogs folder as required
    fragments:
    - fix_changelog_file_location.yaml
    release_date: '2020-12-08'
  2.0.0:
    changes:
      breaking_changes:
      - If added custom sub plugins in your collection move from old location `plugins/<sub-plugin-name>`
        to the new location `plugins/sub_plugins/<sub-plugin-name>` and update the
        imports as required
      - Move sub plugins cli_parsers, fact_diff and validate to `plugins/sub_plugins`
        folder
      - The `cli_parsers` sub plugins folder name is changed to `cli_parse` to have
        consistent naming convention, that is all the cli_parse subplugins will now
        be in `plugins/sub_plugins/cli_parse` folder
    fragments:
    - 32_doc_updates.yaml
    - sub_plugins_dir_change.yaml
    - upcap_ansible.yaml
    release_date: '2021-01-29'
  2.0.1:
    changes:
      bugfixes:
      - Fix ansible.utils.cli_parse action plugin to support old cli_parse sub-plugin
        structure in ansible.netcommon collection.
    fragments:
    - ansible-doc.yaml
    - cli_parse_fix.yaml
    release_date: '2021-02-25'
  2.0.2:
    changes:
      bugfixes:
      - Fix cli_parse template_path read error (https://github.com/ansible-collections/ansible.utils/pull/51).
      - Fix jsonschema input data format checking (https://github.com/ansible-collections/ansible.utils/pull/50).
    fragments:
    - cli_parse_errors_return.yaml
    - jsonschema_data_validation_fix.yaml
    release_date: '2021-03-29'
  2.1.0:
    changes:
      bugfixes:
      - Add missing test requirements (https://github.com/ansible-collections/ansible.utils/pull/57).
      minor_changes:
      - Add from_xml and to_xml fiter plugin (https://github.com/ansible-collections/ansible.utils/pull/56).
    fragments:
    - 63-add_ignore_txt.yml
    - add-xmltojson-and-jsontoxml-filter.yaml
    - add_missing_test_requirements.yml
    - fix_tests.yaml
    release_date: '2021-04-27'
  2.2.0:
    changes:
      minor_changes:
      - Add in_any_network, in_network, in_one_network test plugins
      - Add ip, ip_address test plugins
      - Add ipv4, ipv4_address, ipv4_hostmask, ipv4_netmask test plugins
      - Add ipv6, ipv6_address, ipv6_ipv4_mapped, ipv6_sixtofour, ipv6_teredo test
        plugins
      - Add loopback, mac, multicast test plugins
      - Add private, public, reserved test plugins
      - Add resolvable test plugins
      - Add subnet_of, supernet_of, unspecified test plugins
    fragments:
    - add_netaddr_test_plugins_1.yml
    - add_netaddr_test_plugins_2.yml
    - add_netaddr_test_plugins_3.yml
    - add_netaddr_test_plugins_4.yml
    - add_netaddr_test_plugins_5.yml
    - add_netaddr_test_plugins_6.yml
    - add_netaddr_test_plugins_7.yml
    - add_netaddr_test_plugins_8.yml
    release_date: '2021-05-17'
  2.3.0:
    changes:
      bugfixes:
      - Also include empty lists and mappings into the output dictionary (https://github.com/ansible-collections/ansible.utils/pull/58).
      doc_changes:
      - Update doc for usable_range filter plugin
      minor_changes:
      - Add usable_range test plugin
    fragments:
    - add_usable_range_filter_plugin.yml
    - empty_list_mapping.yml
    - improve_coverage_for_filter_plugins.yaml
    - update_doc_for_usable_range_filter_plugin.yml
    release_date: '2021-06-22'
